//! Optional design-time Alloy backend: model generation, execution, witness mapping.
//!
//! Alloy is a cross-check, never a requirement. Egeria's static analyses answer
//! the same questions more cheaply for the common cases; this crate exists to
//! validate them differentially and to reach properties that genuinely need
//! bounded relational reasoning.
//!
//! Two rules govern this crate:
//!
//! * `.als` models are generated by trusted Rust code from the IR, never
//!   authored by a language model — otherwise a weakened specification could be
//!   "proven".
//! * Nothing here may become a runtime dependency of a compiled artifact. Tests
//!   skip when no JVM or JAR is present, and fail hard only when
//!   `EGERIA_REQUIRE_ALLOY=1` is set (as CI does).
//!
//! This crate is a stub. See the open issues in milestone `V1-M2`.
